export namespace ENVIRONMENTS {
  export enum VARIABLES {
    PORT = 'PORT',
    MS_AUTH_API = 'MS_AUTH_API',
    MS_TRANSACTION_API = 'MS_TRANSACTION_API',
    MS_TRANSACTION_TCP_HOST = 'MS_TRANSACTION_TCP_HOST',
    MS_TRANSACTION_TCP_PORT = 'MS_TRANSACTION_TCP_PORT',
    MS_TRANSACTION_KAFKA = 'MS_TRANSACTION_KAFKA',
  }
}
